@startuml
skinparam ParticipantPadding 10

participant "Frontend" << JavsScript >>
participant "/* generated */\nclass HelloService" as jsService << JavaScript >>
participant "@VaadinService\n class HelloService" as javaService << Java >>

Frontend -> jsService: await greet("User");
jsService -> javaService: POST JSON Request
...
jsService <-- javaService: POST JSON Response
Frontend <-- jsService: "Hello, User!"
@enduml