@startuml
skinparam ParticipantPadding 10

participant "app.ts" as Frontend
participant "generated/DateService.ts" as tsService
participant "DateService.java" as javaService

Frontend -> tsService: await getDayOfYear(new Date());
tsService -> javaService: POST JSON Request
...
tsService <-- javaService: POST JSON Response
Frontend <-- tsService: 256
@enduml
